-- MySQL Script generated by MySQL Workbench
-- Sun Aug 31 18:36:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TCC` DEFAULT CHARACTER SET utf8 ;
USE `TCC` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `tipo` ENUM('ADMINISTRADOR', 'PROFESSOR') NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`material` (
  `idmaterial` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `descricao` TEXT(600) NOT NULL,
  `categoria` VARCHAR(100) NOT NULL,
  `quantidade` INT NOT NULL,
  `estado_conservacao` ENUM("NOVO", "GASTO", "DESTRUIDO") NOT NULL,
  `local_guardado` VARCHAR(100) NOT NULL,
  `idade_recomendada` INT NOT NULL,
  `foto_capa` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idmaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`material_foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`material_foto` (
  `idmaterial_foto` INT NOT NULL AUTO_INCREMENT,
  `url_foto` VARCHAR(255) NOT NULL,
  `material_idmaterial` INT NOT NULL,
  PRIMARY KEY (`idmaterial_foto`),
  INDEX `fk_material_foto_material1_idx` (`material_idmaterial` ASC) VISIBLE,
  CONSTRAINT `fk_material_foto_material1`
    FOREIGN KEY (`material_idmaterial`)
    REFERENCES `mydb`.`material` (`idmaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calendario_disponibilidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`calendario_disponibilidade` (
  `idcalendario_disponibilidade` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `status` ENUM("DISPONIVEL", "BLOQUEADO") NOT NULL,
  `material_idmaterial` INT NOT NULL,
  PRIMARY KEY (`idcalendario_disponibilidade`),
  INDEX `fk_calendario_disponibilidade_material1_idx` (`material_idmaterial` ASC) VISIBLE,
  CONSTRAINT `fk_calendario_disponibilidade_material1`
    FOREIGN KEY (`material_idmaterial`)
    REFERENCES `mydb`.`material` (`idmaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`solicitacao_externa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`solicitacao_externa` (
  `idsolicitacao_externa` INT NOT NULL AUTO_INCREMENT,
  `data_solicitacao` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `descricao` TEXT(600) NOT NULL,
  `status` ENUM("PENDENTE", "APROVADO", "RECUSADO") NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `material_idmaterial` INT NOT NULL,
  PRIMARY KEY (`idsolicitacao_externa`),
  INDEX `fk_solicitacao_externa_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_solicitacao_externa_material1_idx` (`material_idmaterial` ASC) VISIBLE,
  CONSTRAINT `fk_solicitacao_externa_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacao_externa_material1`
    FOREIGN KEY (`material_idmaterial`)
    REFERENCES `mydb`.`material` (`idmaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`relatorio` (
  `idrelatorio` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM("MATERIAIS_FATA", "MATERIAIS_QUASE_FIM", "MATERIAIS_MAIS_UTILIZADOS", "TODOS_MATERIAIS") NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `data_geracao` DATE NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idrelatorio`),
  INDEX `fk_relatorio_usuario_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_relatorio_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`notificacao` (
  `idnotificacao` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(150) NOT NULL,
  `mensagem` TEXT(500) NOT NULL,
  `tipo` ENUM("INFO", "ALERTA", "SOLICITACAO", "SISTEMA") NOT NULL,
  `status` ENUM("NAO_LIDA", "LIDA") NOT NULL,
  `data_criacao` DATE NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idnotificacao`),
  INDEX `fk_notificacao_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_notificacao_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
